image: docker
services:
  - docker

stages:
  - build
  - push

variables:
  IMAGE_NAME: lychie-back-repo

build_image:
  stage: build
  script:
    - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/$AWS_REGISTRY_NAME
    - docker build -t $IMAGE_NAME .
    - docker tag $IMAGE_NAME:latest public.ecr.aws/$AWS_REGISTRY_NAME/$IMAGE_NAME:latest

push_image:
  stage: push
  script:
    - docker push public.ecr.aws/$AWS_REGISTRY_NAME/$IMAGE_NAME:latest
